#pragma once

#include <cstdint>
#include <limits>

#include <glad/glad.h>
#include "GLFW/glfw3.h"

namespace R2D
{
	// Type alias for uniforms
	using GLUniformLocation = int;

	// Vertex attribute defines
	using AttribCount = uint8_t;

	// Buffer handle type (for VAOs)
	using BufferHandle = uint8_t;

	// Handle bit count
	auto constexpr BUFFER_HANDLE_BITS{ std::numeric_limits<BufferHandle>::digits };

	enum class ATTRIBUTE_TYPE : GLenum
	{
		BYTE = GL_BYTE,
		UBYTE = GL_UNSIGNED_BYTE,
		SHORT = GL_SHORT,
		USHORT = GL_UNSIGNED_SHORT,
		INT = GL_INT,
		UINT = GL_UNSIGNED_INT,
		FLOAT = GL_FLOAT,
		HALF_FLOAT = GL_HALF_FLOAT
	};

	// Uniform Types
	enum class UNIFORM_TYPE
	{
		SAMPLER = 0,
		FLOAT,
		INT,
		UINT,

		VEC2,
		VEC3,
		VEC4,

		IVEC2,
		IVEC3,
		IVEC4,

		UVEC2,
		UVEC3,
		UVEC4,

		MAT2,
		MAT3,
		MAT4
	};

	// Buffer usage types
	enum class BUFFER_USAGE : GLenum
	{
		NONE = 0,
		// glNamedBufferData 
		STREAM_DRAW = GL_STREAM_DRAW,
		STREAM_READ = GL_STREAM_READ,
		STREAM_COPY = GL_STREAM_COPY,
		STATIC_DRAW = GL_STATIC_DRAW,
		STATIC_READ = GL_STATIC_READ,
		STATIC_COPY = GL_STATIC_COPY,
		DYNAMIC_DRAW = GL_DYNAMIC_DRAW,
		DYNAMIC_READ = GL_DYNAMIC_READ,
		DYNAMIC_COPY = GL_DYNAMIC_COPY,

		// glNamedBufferStorage 
		DYNAMIC_STORE = GL_DYNAMIC_STORAGE_BIT,
		MAP_READ = GL_MAP_READ_BIT,
		MAP_WRITE = GL_MAP_WRITE_BIT,
		MAP_PERSISTENT = GL_MAP_PERSISTENT_BIT,
		MAP_COHERENT = GL_MAP_COHERENT_BIT,
		CLIENT_STORE = GL_CLIENT_STORAGE_BIT,
		MAP_USAGE = GL_MAP_PERSISTENT_BIT | GL_MAP_COHERENT_BIT | GL_MAP_READ_BIT | GL_MAP_WRITE_BIT,
		DYNAMIC_MAP_STORE = DYNAMIC_STORE | MAP_USAGE
	};

	// Buffer bind context
	enum class BUFFER_TARGET : GLenum
	{
		VERTEX = GL_ARRAY_BUFFER,
		INDEX = GL_ELEMENT_ARRAY_BUFFER,
		INSTANCE = GL_ARRAY_BUFFER,
		UNIFORM = GL_UNIFORM_BUFFER
	};

	// Index Buffer type
	enum class INDEX_TYPE : GLenum
	{
		UINT8 = GL_UNSIGNED_BYTE,
		UINT16 = GL_UNSIGNED_SHORT,
		UINT32 = GL_UNSIGNED_INT
	};

	// Shader Program enum
	using SHADER_PROGRAM_VALUE = uint8_t;

	// Texture Formats
	enum class TEXTURE_FORMAT : GLenum
	{
		R8 = GL_R8,
		R8I = GL_R8I,
		R8UI = GL_R8UI,
		R16F = GL_R16F,
		R32F = GL_R32F,
		R32U = GL_R32UI,
		R32I = GL_R32I,
		RGB8 = GL_RGB8,
		RGB32F = GL_RGB32F,
		RGBA8 = GL_RGBA8,
		RGBA16F = GL_RGBA16F,
		RGBA32F = GL_RGBA32F,
		DEPTH24 = GL_DEPTH_COMPONENT24,
		DEPTH32F = GL_DEPTH_COMPONENT32F
	};

	// Draw modes (might have more in the future)
	enum class DRAW_MODE : GLenum
	{
		TRIANGLES = GL_TRIANGLES,
		TRIANGLE_FAN = GL_TRIANGLE_FAN,
		TRIANGLE_STRIP = GL_TRIANGLE_STRIP,
		LINES = GL_LINES,
		LINE_STRIP = GL_LINE_STRIP,
		LINE_LOOP = GL_LINE_LOOP,
		POINTS = GL_POINTS
	};

	enum class BLEND_MODES : GLenum
	{
		ONE = GL_ONE,
		ZERO = GL_ZERO,
		SRC_ALPHA = GL_SRC_ALPHA,
		ONE_MINUS_SRC_ALPHA = GL_ONE_MINUS_SRC_ALPHA,
		DST_ALPHA = GL_DST_ALPHA,
		ONE_MINUS_DST_ALPHA = GL_ONE_MINUS_DST_ALPHA
	};

	enum class BLEND_EQN : GLenum
	{
		ADD = GL_FUNC_ADD,
		SUBTRACT = GL_FUNC_SUBTRACT,
		REVERSE_SUBTRACT = GL_FUNC_REVERSE_SUBTRACT,
		MIN = GL_MIN,
		MAX = GL_MAX
	};

	enum class FRONT_FACE : GLenum
	{
		CCW = GL_CCW,
		// OpenGL default front face is CCW
		CW = GL_CW
	};

	enum class DEPTH_COMP : GLenum
	{
		NEVER = GL_NEVER,
		LESS = GL_LESS,
		EQUAL = GL_EQUAL,
		LESS_OR_EQUAL = GL_LEQUAL,
		GREATER = GL_GREATER,
		NOT_EQUAL = GL_NOTEQUAL,
		GREATER_OR_EQUAL = GL_GEQUAL,
		ALWAYS = GL_ALWAYS,
	};


	enum class TEX_PARAM_NAMES : GLenum
	{
		TEXTURE_WRAP_S = GL_TEXTURE_WRAP_S,
		TEXTURE_WRAP_T = GL_TEXTURE_WRAP_T,
		TEXTURE_WRAP_R = GL_TEXTURE_WRAP_R,
		TEXTURE_MIN_FILTER = GL_TEXTURE_MIN_FILTER,
		TEXTURE_MAG_FILTER = GL_TEXTURE_MAG_FILTER,
		TEXTURE_COMPARE_MODE = GL_TEXTURE_COMPARE_MODE,
	};

	enum class TEX_PARAM_VALUES : GLenum
	{
		NONE = GL_NONE,
		NEAREST = GL_NEAREST,
		LINEAR = GL_LINEAR,
		NEAREST_MIPMAP_NEAREST = GL_NEAREST_MIPMAP_NEAREST,
		LINEAR_MIPMAP_NEAREST = GL_LINEAR_MIPMAP_NEAREST,
		NEAREST_MIPMAP_LINEAR = GL_NEAREST_MIPMAP_LINEAR,
		LINEAR_MIPMAP_LINEAR = GL_LINEAR_MIPMAP_LINEAR,
		CLAMP_TO_EDGE = GL_CLAMP_TO_EDGE,
		MIRRORED_REPEAT = GL_MIRRORED_REPEAT,
		REPEAT = GL_REPEAT,
		COMPARE_REF_TO_TEXTIRE = GL_COMPARE_REF_TO_TEXTURE
	};

	enum class SHADER_VARIABLE_TYPE
	{
		INT = GL_INT,
		INT_VEC2 = GL_INT_VEC2,
		INT_VEC3 = GL_INT_VEC3,
		INT_VEC4 = GL_INT_VEC4,
		UINT = GL_UNSIGNED_INT,
		UNSIGNED_INT_VEC2 = GL_UNSIGNED_INT_VEC2,
		UNSIGNED_INT_VEC3 = GL_UNSIGNED_INT_VEC3,
		UNSIGNED_INT_VEC4 = GL_UNSIGNED_INT_VEC4,
		FLOAT = GL_FLOAT,
		FLOAT_VEC2 = GL_FLOAT_VEC2,
		FLOAT_VEC3 = GL_FLOAT_VEC3,
		FLOAT_VEC4 = GL_FLOAT_VEC4,
		DOUBLE = GL_DOUBLE,
		DOUBLE_VEC2 = GL_DOUBLE_VEC2,
		DOUBLE_VEC3 = GL_DOUBLE_VEC3,
		DOUBLE_VEC4 = GL_DOUBLE_VEC4,
		// There are more supported, but this will do for now
	};

	enum class IMAGE_ACCESS
	{
		READ_ONLY = GL_READ_ONLY,
		WRITE_ONLY = GL_WRITE_ONLY,
		READ_WRTIE = GL_READ_WRITE
	};
}
